web/cloudmatch/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Jul 17 Login Change
from django.views.generic import RedirectView


from wisconsin import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name ='index'),
    url(r'^lake_to_site/(?P<id>.+)/', views.lake_to_site, name ='lake_to_site'),
    url(r'^lake_to_site_download/(?P<id>.+)/', views.lake_to_site_download, name ='lake_to_site_download'),
    url(r'^site_to_lake/', views.site_to_lake, name ='site_to_lake'),
    url(r'^waterbodies/(?P<page>\d+)/', views.waterbodies, name ='waterbodies'),
    url(r'^lake/(?P<id>.+)/', views.lake_detail, name ='lake_detail'),
    url(r'^sites/(?P<page>\d+)/', views.sites, name ='sites'),
    url(r'^site/(?P<id>.+)/', views.site_detail, name ='site_detail'),
    url(r'^bbs/', views.bb, name ='bbs'),
    url(r'^bb/(?P<id>.+)/', views.bb_detail, name ='bb_detail'),
    url(r'^characteristics/', views.characteristics, name ='characteristics'),
    url(r'^characteristics_summary/(?P<char>.+)/', views.characteristics_summary, name ='characteristics_summary'),
    url(r'^characteristics_graph/(?P<charac>.+)/', views.characteristics_graph, name ='characteristics_graph'),
    # July 17 Login Change
    #url(r'^frontend/', include('frontend.urls',namespace='frontend',app_name='frontend')),
    #url(r'^$', RedirectView.as_view(permanent=False, url='/frontend/ulogin/')),
    #url(r'^', include('frontend.urls')),
    # url(r'^frontend/', include('frontend.urls')),
    # July 17 End


    # url(r'^accounts/login/$', login, {'template_name': 'admin/login.html'}, name='login'),
    # url(r'^accounts/logout/$', logout, name='logout'),
    # url(r'^', include('frontend.urls')),
    # url(r'^login/$', login, {'template_name': 'login.html', 'authentication_form': LoginForm}),
    # url(r'^logout/$', logout, {'next_page': '/login'}),
]

urlpatterns += staticfiles_urlpatterns()

web/frontend/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'frontend'
urlpatterns = [
    # ...
    # Login and home page related URLs
    url(r'^homepage/$', homepage, name='homepage'),
    url(r'^main_page/$', main_page, name='main_page'),
    url(r'^$', home, name='home'),
    url(r'^ulogin/$', auth_views.login, {'template_name': 'userreg/home.html'}, name='login'),
    url(r'^ulogout/$', auth_views.logout, {'template_name': 'userreg/logged_out.html'},  name='logout'),
    url(r'^register/$', register, name='register'),
    url(r'^index/$', index, name='index'),

    # Upload dataset URL
    url(r'upload_data/$', upload_data, name='upload_data'),

]

web/frontend/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField, JSONField


# Create your models here.

class DataFile(models.Model):
    file = models.FileField(blank=True, upload_to="data")

    def __str__(self):
        return self.file.name


# YG - creating a model to store dag related information. This model will be used by meta core to store
# DAG related information and to track current DAG status.
class Workflow(models.Model):
    STATES = (
        ('CREATED', 'Workflow created'),
        ('STARTED', 'Workflow started'),
        ('IN_PROGRESS', 'Workflow in progress'),
        ('COMPLETED', 'Workflow completed'),
        ('ERROR', 'Error in workflow'),
        ('CANCELLED', 'Workflow cancelled'),
    )
    name = models.CharField(max_length=50, null=True, blank=True)
    owner = models.ForeignKey("auth.User")
    template_id = models.CharField(max_length=50, null=True, blank=True)
    current_fragment_id = models.CharField(max_length=100, null=True, blank=True)
    status = models.CharField(choices=STATES, max_length=50, blank=True, null=True)
    workflow = models.CharField(max_length=2000, null=True, blank=True)
    info = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return str(self.id)

web/frontend/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django import forms
from django.utils.safestring import mark_safe
from django.contrib.auth.forms import AuthenticationForm
import pandas as pd
from io import BytesIO
from .tasks import *
import re


class PersonalInfoForm(forms.Form):
    job_name = forms.CharField(label='Job Name', max_length=100,
                               widget=forms.TextInput(attrs={'placeholder': 'Enter Job Name'}))
    email = forms.EmailField(label='Email',
                             widget=forms.TextInput(attrs={'placeholder': 'Enter Email address to notify'}))
    email2 = forms.EmailField(label='Confirm Email',
                              widget=forms.TextInput(attrs={'placeholder': 'Confirm you Email address'}))


# YG
class UploadDatasetForm(forms.Form):
    wfid = forms.CharField(label='Workflow ID',
                           max_length=100, required=True,
                           widget=forms.TextInput(attrs={'placeholder': 'Workflow ID'}))
    fragid = forms.CharField(label='Fragment ID', max_length=100, required=True,
                             widget=forms.TextInput(attrs={'placeholder': 'Fragment ID'}))
    name = forms.CharField(label='Name*',
                           help_text='The file uploader will appear once you enter the dataset name',
                           max_length=100, required=True,
                           widget=forms.TextInput(attrs={'placeholder': 'Please enter your dataset name'}))
    description = forms.CharField(label='Description (optional)', max_length=100, required=False,
                                  widget=forms.Textarea(attrs={'placeholder': 'Describe your data here.', 'rows': '2'}))

    docfile = forms.FileField(label='Choose file')


class RegistrationForm(forms.Form):
    username = forms.CharField(label='Username',
                               max_length=100, required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Please enter a username'}))
    password1 = forms.CharField(label='Password',
                                max_length=100, required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Please enter a password'}))
    password2 = forms.CharField(label='Re-enter password',
                                max_length=100, required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Please reenter your password'}))
    # email = forms.CharField(label='Email*',max_length=100, required=True,
    #                        widget=forms.TextInput(attrs={'placeholder': 'Please enter a username'}))
    email = forms.EmailField(label='Email', required=True)

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
                return password2
        raise forms.ValidationError('Passwords do not match.')

    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError('Username can only contain alphanumeric characters and the underscore.')
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError('Username is already taken.')


class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
    password = forms.CharField(label="Password", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'password'}))


class FileUploadForm(forms.Form):
    docfile = forms.FileField(label='Select a file',
                              help_text='max. 42 megabytes')
    days = forms.ChoiceField(widget=forms.Select(), choices=([('1', '1'), ('2', '2'), ('3', '3'), ]), initial=1,
                             required=False)


class FileUploadFormList(forms.Form):
    def __init__(self, *args, **kwargs):
        self.header = kwargs.pop('header')
        options = []
        for head in self.header:
            options.append((head, head))
        super(FileUploadFormList, self).__init__(*args, **kwargs)
        self.fields['list'] = forms.ChoiceField(widget=forms.Select(
            attrs={'class': 'selectpicker show-tick show-menu-arrow', 'data-width': "fit",
                   'data-style': "btn-warning"}), choices=[(o, o) for o in self.header], initial=self.header[0],
            required=False)


def getPairCountDropDownField():
    numbers = range(1, 21)
    return forms.ChoiceField(widget=forms.Select(
        attrs={'class': 'selectpicker show-tick show-menu-arrow', 'data-width': "fit", 'data-style': "btn-warning"}),
        choices=[(i, i) for i in numbers], initial=numbers[4], required=True)


class SelectModeForm(forms.Form):
    pair_count = getPairCountDropDownField()
    docfile = forms.FileField(required=False, label='Select a file', help_text='max. 42 megabytes')


class SelectCrowdModeForm(forms.Form):
    docfile = forms.FileField(required=False, label='Select a file', help_text='max. 42 megabytes')
    pair_count = getPairCountDropDownField()
    reward_amount = forms.FloatField(label='Reward amount for labelling each batch',
                                     help_text='Tooltip description goes here for reward amount',
                                     widget=forms.TextInput(
                                         attrs={'type': 'number', 'step': 0.01, 'class': "form-control", 'min': 0}))
    assignment_duration_hit = forms.IntegerField(label='Assignment duration for this HIT (hours)',
                                                 help_text='Tooltip description goes here for assignment duration',
                                                 widget=forms.TextInput(
                                                     attrs={'type': 'number', 'class': "form-control", 'min': 0}))
    auto_approval_delay = forms.IntegerField(label='Auto Approval Delay (days)',
                                             help_text='Tooltip description goes here for auto approval delay',
                                             widget=forms.TextInput(
                                                 attrs={'type': 'number', 'class': "form-control", 'min': 0}))
    hit_lifetime = forms.IntegerField(label='HIT lifetime (days)',
                                      help_text='Tooltip description goes here for hit lifetime',
                                      widget=forms.TextInput(
                                          attrs={'type': 'number', 'class': "form-control", 'min': 0}))
    initial_assignment = forms.IntegerField(label='Number of Initial Assignment',
                                            help_text='Tooltip description goes here for initial assignment',
                                            widget=forms.TextInput(
                                                attrs={'type': 'number', 'class': "form-control", 'min': 0}))
    mturk_access_key = forms.CharField(label='MTurk Access Key', max_length=300,
                                       help_text='Tooltip description goes here for mturk_access_key',
                                       widget=forms.TextInput(attrs={'type': 'text', 'class': "form-control"}))
    mturk_secret_key = forms.CharField(label='MTurk Secret Key', max_length=300,
                                       help_text='Tooltip description goes here for mturk_secret_key',
                                       widget=forms.TextInput(attrs={'type': 'text', 'class': "form-control"}))


class JobProgressForm(forms.Form):
    job_id = forms.IntegerField(label='Job ID', help_text='Enter Job ID to get the progress',
                                widget=forms.TextInput(attrs={'type': 'number', 'class': "form-control", 'min': 1}))

web/frontend/templates/frontend/create/personal_info.html
{% extends 'frontend/base.html' %}
{% load i18n widget_tweaks %}
{% block content %}

<div class="row" style="padding-top: 30px">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Create a new job</h3>
      </div>
      <div class="panel-body">
          <h4>Step 1 - Add Personal Information</h4>
          <form action="#" class="form-horizontal" role="form" method="post">
            {% csrf_token %}
            {% for field in form %}
                {% if field.errors %}
                    <div class="form-group has-error">
                        <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                        <div class="col-sm-10">
                            {{ field|attr:"class:form-control" }}
                            <span class="help-block">
                                {% for error in  field.errors %}{{ error }}{% endfor %}
                            </span>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label" for="id_{{ field.name }}">{{ field.label }}</label>
                        <div class="col-sm-10">
                            {{ field|attr:"class:form-control" }}
                            {% if field.help_text %}
                                <p class="help-block"><small>{{ field.help_text }}</small></p>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <a href="{% url 'frontend:index' %}" class="btn btn-default">Cancel</a>
                    <button type="submit" class="btn btn-primary">{% trans "Next" %}</button>
                </div>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

web/frontend/templates/frontend/create/upload_data.html
{% extends 'frontend/base.html' %}
{% load i18n widget_tweaks %}
{% block content %}
{% load static %}

<div class="row" style="padding-top: 30px">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Upload a new dataset</h3>
            </div>
        </div>
        <div style="display: none">
            <p>
            <div id="wf_id">{{ wf_id }}</div>
            <div id="frag_id">{{ frag_id }}</div>
            </p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-7">
        <div class="panel-body">
            <form action="#" method="post" enctype="multipart/form-data" role="form" class="form-horizontal">
                {% csrf_token %}
                <div class="form-group" style="display: none;">
                    <label for="id_wfid" class="col-sm-2 control-label">
                        Workflow ID
                    </label>
                    <div class="col-sm-10">
                        {{ form.wfid|attr:"class:form-control" }}
                    </div>
                </div>

                <div class="form-group" style="display: none;">
                    <label for="id_fragid" class="col-sm-2 control-label">
                        Fragment ID
                    </label>
                    <div class="col-sm-10">
                        {{ form.fragid|attr:"class:form-control" }}
                    </div>
                </div>


                <div class="form-group">
                    {{ form.non_field_errors }}
                    <label for="id_name" class="col-sm-2 control-label">
                        Dataset name<span class='required'>*</span>
                    </label>
                    <div class="col-sm-10">
                        {{ form.name|attr:"class: form-control" }}
                    </div>
                    <div class="col-sm-10 pull-right" id="wait_for_upload">
                        {% if form.name.help_text %}
                            <p><small class="help-block">{{ form.name.help_text}} </small></p>
                        {% endif %}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_description" class="col-sm-2 control-label">
                        Description (optional)
                    </label>
                    <div class="col-sm-10">
                        {{ form.description|attr:"class:form-control" }}
                    </div>
                </div>
                <div class="form-group" style="display: none;" id="upload_form_group">
                    <label class="col-sm-2 control-label">Upload file<span class='required'>*</span></label>
                    <div class="col-sm-10">
                        {{ form.docfile }}
                        <p class="help-block">
                            Only <strong>.csv</strong> files.
                        </p>
                        <p>
                            <div id="fileName"></div>
                            <div id="fileSize"></div>
                            <div id="fileType"></div>
                        </p>
                    </div>
                </div>
                <div class="form-group" id="upload_btn" style="display: none">
                    <label class="col-sm-2 control-label"></label>
                    <div class="col-sm-10">
                        <input type="button" name="theButton" id="up-step" value="Upload" class="btn btn-success disabled">
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-10 col-sm-offset-2" id="progress" style="display: none;">
                        <p style="font-size: large; font-family: Roboto;" id="upload_message"><i class="fa fa-refresh fa-spin"></i> Uploading ...</p>
                        <div class="progress">
                            <div class="progress-bar progress-bar-info"></div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-10 col-sm-offset-2" id="profile_msg" style="display: none;">
                        <p id="profile_text">
                            Next, CloudMatcher is going to profile your data. To be precise, it will look into the dataset you have
                            uploaded and identify attribute list, unique attributes, missing values, etc. Based on the input data size
                            this step may take few seconds to complete.
                        </p>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-10 col-sm-offset-2" id="profiling" style="display: none;">
                        <p style="font-size: large; font-family: Roboto;" id="profile_message"><i class="fa fa-refresh fa-spin"></i>  We are profiling your uploaded dataset. Please wait ...</p>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-10 col-sm-offset-2" id="profile_btn" style="display: none;">
                        <p style="font-size: large; font-family: Roboto;">
                            For profiling statistics <input type="button" name="theButton" id="profile" value="click here."  style="color: #5cb85c; background: none; border: none; margin: 0; padding: 0; border-bottom: 1px solid #1e2f45;">
                        </p>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-10 col-sm-offset-2" id="get_confirm_msg" style="display: none;">
                        <p>
                        <input type="button" style="height: 40px; width: 140px" name="YesButton" id="accept-step" value="Accept & Continue" class="btn btn-success disabled">
                        <input type="button" style="height: 40px; width: 140px" name="NoButton" id="cancel-step" value="Cancel Upload" class="btn btn-danger disabled">
                        </p>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="col-md-5">
        <p>
            <h4>Please follow this upload format:</h4>
            <img id="example_csv" class="img-responsive img-thumbnail" src={% static "images/example_csv.png" %}/>
        </p>
        <p>
            The file-to-be uploaded should have a header which contains the name of each column followed by data in
            the subsequent rows. We encourage the first column in the file to be a unique column but we don't force it.
            If we don't find any primary key (unique column), CloudMatcher adds a unique key to the dataset.
        </p>
    </div>

</div>
{% endblock %}
{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
  <script type="text/javascript">

    $("#accept-step[type='button']").click(function () {
        var wf_id = document.getElementById('wf_id').innerHTML;
        $.ajax({
            type: 'GET',
            url: '/get_profile_confirmation/',
            dataType: 'json',
            data: "wf_id=" + wf_id,
            success: function (e, data) {
                console.log(data);
                console.log(e['workflow_status']);
                var workflow_status = e['workflow_status'];
                if (workflow_status === true) {
                    window.location = '/index';
                }
            }
        })
    });

    $("#cancel-step[type='button']").click(function () {
        var wf_id = document.getElementById('wf_id').innerHTML;
        var status = "cancel";
        $.ajax({
            type: 'GET',
            url: '/update_dag/',
            dataType: 'json',
            data: "wf_id=" + wf_id + "&status=" + status,
            success: function (e, data) {
                console.log(data);
                console.log(e['dag_status']);
                window.location = '/index/';
            }
        })
    });

    $("#profile[type='button']").click(function () {
        var wf_id = document.getElementById('wf_id').innerHTML;
        window.open('/see_profile?wf_id=' + wf_id);
    });

  </script>
{% endblock %}

web/frontend/templates/frontend/create/view_profile.html
{% extends 'frontend/base.html' %}
{% load i18n widget_tweaks %}
{% load bootstrap3 %}
{% block content %}
<div class="container">
    <div class="row" style="padding-top: 10px">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title"></h3>
                </div>
                <div class="panel-body">
                    <div class="card">
                      <h3 class="card-header">Uploaded dataset statistics: {{ dag_name }}</h3>
                    </div>

                    <div class="col-md-4">
                        <br>
                        <p class="h4">Dataset info</p>
                        <table class="table table-striped table-bordered table-hover">
                            <tr>
                                <th>Number of records</th>
                                <td>{{ num_of_rows }}</td>
                            </tr>
                            <tr>
                                <th>Number of attributes</th>
                                <td>{{ num_of_attrs }}</td>
                            </tr>
                            <tr>
                                <th>Total size in memory</th>
                                <td>{{ mem_size }}</td>
                            </tr>
                            <tr>
                                <th>Average record size in memory</th>
                                <td>{{ avg_record_size }}</td>
                            </tr>
                        </table>
                        <p> <a href="{% url 'frontend:index' %}">CloudMatcher</a> profiles the uploaded dataset, identifies the basic information
                            required for the user to verify if the dataset uploaded is indeed what he/she
                            wanted to explore/clean or use as one of the dataset in entity matching.
                        </p>
                    </div>
                    <div class="col-md-8">
                        <br>
                        <p class="h4">Attribute info</p>
                        <div class="well-small" style="overflow: scroll; height: 250px; border-bottom: groove">
                        <table class="table table-striped table-bordered table-hover">
                            <thead class="thead-inverse" style="background-color: #eea43c;">
                                <tr>
                                    <th style="text-align: center;">Attribute Name</th>
                                    <th style="text-align: center;">Unique (T/F)</th>
                                    <th style="text-align: center;">Attr Type</th>
                                    <th style="text-align: center;">Missing Values (%)</th>
                                    <th style="text-align: center;">Unique Values (%)</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for r in attr_info %}
                                    <tr>
                                        {% for cell_val in r %}
                                        <td style="text-align: center;">{{ cell_val }}</td>
                                        {% endfor %}
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="well" style="overflow: scroll">
                            <h4>Sample rows</h4>
                            <table class="table table-striped table-bordered table-hover">
                                <thead class="thead-inverse" style="background-color: #eea43c;">
                                    <tr>
                                        {% for column in headers %}
                                            <th style="text-align: center;">{{ column }}</th>
                                        {% endfor %}
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for row in rows %}
                                        <tr>
                                        {% for cell in row %}
                                        <td style="text-align: center;">{{ cell }}</td>
                                        {% endfor %}
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div id="get_config_msg" style="display: none;">
                            <p>
                                <h4>
                                    Please accept the statistics to complete the job or hit cancel if you want to cancel this upload.
                                    <hr>
                                    <p>
                                    <input type="button" style="height: 40px; width: 70px" name="YesButton" id="yes-step" value="Accept" class="btn btn-success disabled">
                                    <input type="button" style="height: 40px; width: 70px" name="NoButton" id="no-step" value="Cancel" class="btn btn-danger disabled">
                                    </p>
                                </h4>
                            </p>
                        </div>
                        <div id="confirming" style="display: none;">
                            <p id="confirm_message"><i class="fa fa-refresh fa-spin"></i><h4></h4></p>
                        </div>
                        <div id="home-page" style="display: none">
                            <a href="{% url 'frontend:index' %}" class="btn btn-primary btn-large" style="width: 70px">Home</a>
                            <a href="{% url 'frontend:upload_data' %}" class="btn btn-success">Upload another dataset</a>
                        </div>
                    </div>
                    <div class="col-md-12" style="display: none">
                        <p>
                            <div id="wf_id">{{ wf_id }}</div>
                            <div id="frag_id">{{ frag_id }}</div>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="center-align">
        <p>&copy; 2017 CloudMatcher.io, UW-Madison.</p>
    </footer>
</div>
{% endblock %}
{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
  <script type="text/javascript">
    window.onload = function () {
        Confirmation()
    };

    function Confirmation() {
        var wf_id = document.getElementById('wf_id').innerHTML;
        $.ajax({
            type: 'GET',
            url: '/get_profile_status/',
            dataType: 'json',
            data: "wf_id=" + wf_id,
            success: function (e, data) {
                console.log(data);
                console.log(e['workflow_status']);
                var workflow_status = e['workflow_status'];
                if (workflow_status != true) {
                    $("#get_config_msg").fadeIn();
                    $('#yes-step').removeClass('disabled');
                    $('#no-step').removeClass('disabled');
                }
                else {
                    $("#home-page").fadeIn();
                }
            }
        })
    }

    $("#yes-step[type='button']").click(function () {
        var wf_id = document.getElementById('wf_id').innerHTML;
        $.ajax({
            type: 'GET',
            url: '/get_profile_confirmation/',
            dataType: 'json',
            data: "wf_id=" + wf_id,
            success: function (e, data) {
                console.log(data);
                console.log(e['workflow_status']);
                var dag_status = e['dag_status'];
                var workflow_status = e['workflow_status'];
                if (workflow_status === true) {
                    $("#confirming").fadeIn();
                    $("#confirm_message").html("Thank you for confirming! We appreciate your input.");
                    $('#yes-step').addClass('disabled');
                    $('#no-step').addClass('disabled')
                    $("#home-page").fadeIn();
                    window.location = '/index/';
                }
            }
        })
    });

  </script>
{% endblock %}