web/cloudmatch/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Jul 17 Login Change
from django.views.generic import RedirectView


from wisconsin import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name ='index'),
    url(r'^lake_to_site/(?P<id>.+)/', views.lake_to_site, name ='lake_to_site'),
    url(r'^lake_to_site_download/(?P<id>.+)/', views.lake_to_site_download, name ='lake_to_site_download'),
    url(r'^site_to_lake/', views.site_to_lake, name ='site_to_lake'),
    url(r'^waterbodies/(?P<page>\d+)/', views.waterbodies, name ='waterbodies'),
    url(r'^lake/(?P<id>.+)/', views.lake_detail, name ='lake_detail'),
    url(r'^sites/(?P<page>\d+)/', views.sites, name ='sites'),
    url(r'^site/(?P<id>.+)/', views.site_detail, name ='site_detail'),
    url(r'^bbs/', views.bb, name ='bbs'),
    url(r'^bb/(?P<id>.+)/', views.bb_detail, name ='bb_detail'),
    url(r'^characteristics/', views.characteristics, name ='characteristics'),
    url(r'^characteristics_summary/(?P<char>.+)/', views.characteristics_summary, name ='characteristics_summary'),
    url(r'^characteristics_graph/(?P<charac>.+)/', views.characteristics_graph, name ='characteristics_graph'),
    # July 17 Login Change
    #url(r'^frontend/', include('frontend.urls',namespace='frontend',app_name='frontend')),
    #url(r'^$', RedirectView.as_view(permanent=False, url='/frontend/ulogin/')),
    #url(r'^', include('frontend.urls')),
    # url(r'^frontend/', include('frontend.urls')),
    # July 17 End


    # url(r'^accounts/login/$', login, {'template_name': 'admin/login.html'}, name='login'),
    # url(r'^accounts/logout/$', logout, name='logout'),
    # url(r'^', include('frontend.urls')),
    # url(r'^login/$', login, {'template_name': 'login.html', 'authentication_form': LoginForm}),
    # url(r'^logout/$', logout, {'next_page': '/login'}),
]

urlpatterns += staticfiles_urlpatterns()

web/frontend/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'frontend'
urlpatterns = [
    # ...
    # Login and home page related URLs
    url(r'^homepage/$', homepage, name='homepage'),
    url(r'^main_page/$', main_page, name='main_page'),
    url(r'^$', home, name='home'),
    url(r'^ulogin/$', auth_views.login, {'template_name': 'userreg/home.html'}, name='login'),
    url(r'^ulogout/$', auth_views.logout, {'template_name': 'userreg/logged_out.html'},  name='logout'),
    url(r'^register/$', register, name='register'),
    url(r'^index/$', index, name='index'),

    # Upload dataset URL
    url(r'upload_data/$', upload_data, name='upload_data'),

]

web/frontend/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField, JSONField


# Create your models here.

class DataFile(models.Model):
    file = models.FileField(blank=True, upload_to="data")

    def __str__(self):
        return self.file.name


# YG - creating a model to store dag related information. This model will be used by meta core to store
# DAG related information and to track current DAG status.
class Workflow(models.Model):
    STATES = (
        ('CREATED', 'Workflow created'),
        ('STARTED', 'Workflow started'),
        ('IN_PROGRESS', 'Workflow in progress'),
        ('COMPLETED', 'Workflow completed'),
        ('ERROR', 'Error in workflow'),
        ('CANCELLED', 'Workflow cancelled'),
    )
    name = models.CharField(max_length=50, null=True, blank=True)
    owner = models.ForeignKey("auth.User")
    template_id = models.CharField(max_length=50, null=True, blank=True)
    current_fragment_id = models.CharField(max_length=100, null=True, blank=True)
    status = models.CharField(choices=STATES, max_length=50, blank=True, null=True)
    workflow = models.CharField(max_length=2000, null=True, blank=True)
    info = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return str(self.id)

web/frontend/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect
from .forms import *
from django.contrib.auth.decorators import login_required
from .models import Workflow
from django.template import RequestContext
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse

import json
import requests
import os


# Create your views here. This login required decorator is to not allow to any view without authenticating
@login_required(login_url="login/")
def home(request):
    return render(request, "home.html")


# This takes in a user name and password to login. This view doesn't require any login
def login_user(request):
    logout(request)
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/homepage/')
    return render_to_response('login.html', context_instance=RequestContext(request))


# This is the view for main page - what users sees when we goes to cloudmatcher.io
def main_page(request):
    if request.POST:
        username = request.POST['form-username']
        password = request.POST['form-password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/frontend/homepage')
    return render(request, 'frontend/welcome/home.html')


# Once the user logs in to cloudmatcher.io - he sees this page as the first thing
@login_required
def homepage(request):
    return render(request, 'frontend/index.html')


# If the user refreshes or goes to home page after login then he will see the index page with updated details
@login_required
def index(request):
    username = request.user.username
    owner = User.objects.get(username=username)
    wf_list = Workflow.objects.filter(owner=owner).exclude(status='COMPLETED').exclude(status='ERROR').exclude(
        status='CANCELLED').order_by('id')

    context = {'wf_list': wf_list, 'state_description': state_description, 'username': username,
               'info_text': info_txt, 'wf_info': wf_info}

    return render(request, 'frontend/index.html', context)


# This view is used to handle new users who would like to register themselves to use CloudMatcher. It uses the
# registration form and the register.html page.
def register(request):
    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = User.objects.create_user(username=form.cleaned_data['username'],
                                            password=form.cleaned_data['password1'],
                                            email=form.cleaned_data['email'])
            return HttpResponseRedirect('/')
        else:
            return render(request, 'userreg/register.html', {'form': form})
    return render(request, 'userreg/register.html')


# This method will send and receive metadata information from Meta Manager. This method will send the data from the
# web application to the meta core and will also process the response received from Meta Manager. This method should
# be very fast and should process all the calls quickly.
def send_receive_meta_manager(input_msg, method):

    # Sending the payload to the meta core by first converting the message into JSON format and then calling the
    # required MM method.
    send_message = json.dumps(input_msg)
    url = URL + method
    req = requests.post(url, data=send_message)

    # Receiving response from the meta core and processing it
    response = json.loads(req.text)
    return response


# Upload data view is used whenever the user wants to upload a new dataset. This view requires the user to
# login into the system.
@login_required
def upload_data(request):
    if request.method == 'POST':
        # Get the form data. For upload_data we know that UploadDatasetForm will be used.
        form = UploadDatasetForm(request.POST, request.FILES)
        # Check if the form is valid (whether all required information was filled or not by the user)
        if form.is_valid():
            # Fetching the workflow id from the request
            wf_id = request.POST['wfid']
            frag_id = request.POST['fragid']

            print('post request: ', request.POST)
            print('post info: ', wf_id)
            print('frag id: ', frag_id)

            # Save the uploaded file first in the uploaded files database
            in_file = request.FILES['docfile']
            submit_by = User.objects.get(username=request.user.username)
            _upload = UploadedFiles.objects.create(owner=submit_by)
            _upload.wf_id = wf_id
            _upload.doc_file = in_file
            _upload.save()

            logger.info('Uploaded file saved successfully to the database: ' + str(_upload.id))
            _up = UploadedFiles.objects.get(pk=_upload.id)
            file_loc = str(_up.doc_file.file.name)
            print(file_loc)

            # Fetching form information and create payload to call meta core rest api
            payload = {'user': request.user.username, 'wf_id': wf_id, 'file_name': request.POST['name'],
                       'info': request.POST['description'], 'file_loc': file_loc, 'celery_status': None,
                       'frag_id': frag_id}

            response_msg = send_receive_meta_manager(payload, 'workflow_update')
            return HttpResponse(json.dumps(response_msg), content_type="application/json")
        else:
            # If the form is not valid, it will be returned back to the user with status error
            logger.info("Invalid form")
    elif request.method == 'GET':
        owner = request.user.username
        # Checking if a Workflow id is already assigned or not
        using_wf_id = request.GET.get('wf_id', False)
        using_frag_id = request.GET.get('frag_id', False)

        # Creating payload to send as message to the create_workflow api of meta manager
        if not using_wf_id:
            payload = {'user': owner, 'template': 'upload_table'}
            received_msg = send_receive_meta_manager(payload, 'create_workflow')

            print('received_msg: ', received_msg)

            # Reading the workflow id and form details received from the Meta Manager (like the form)
            wf_id = received_msg['wf_id']
            message = received_msg['message'][0]
            print('Message: ', message)
            current_frag_id = int(message['current_frag_id'])
        else:
            wf_id = using_wf_id
            current_frag_id = using_frag_id

        print('GET request: ', wf_id, current_frag_id)

        # Returning the html page back to the user
        form = UploadDatasetForm(initial={'wfid': wf_id, 'fragid': current_frag_id})
        return render(request, 'frontend/create/upload_data.html', {'form': form, 'wf_id': wf_id,
                                                                    'frag_id': current_frag_id})

    msg = {
        'status': 'ERROR',
        'info': 'Error in processing the form post method!'
    }
    return HttpResponse(json.dumps(msg), content_type="application/json")

web/frontend/templates/frontend/add_label_neg_examples.html
{% extends 'frontend/base.html' %}
{% load bootstrap3 %}

{% block title %}Create additional negative matches {% endblock %}
{% block content %}

{# Display a form #}
<form action="{% url 'frontend:add_label_neg_examples' job.id %}" method="post" class="form">
  {% csrf_token %}
  <Table>
  <tr>
  {% for pairA in form.firstPairA %}
  <td>{% bootstrap_field pairA %}</td>
  {% endfor %} 
  </tr>
  <tr>
  {% for pairB in form.firstPairB %}
  <td>{% bootstrap_field pairB show_label=False %}</td>
  {% endfor %} 
  </tr>
  </table>

  {% if form.hasSecondPair %}
  <Table>
  <tr>
  {% for pairA in form.secondPairA %}
  <td>{% bootstrap_field pairA %}</td>
  {% endfor %} 
  </tr>
  <tr>
  {% for pairB in form.secondPairB %}
  <td>{% bootstrap_field pairB show_label=False %}</td>
  {% endfor %} 
  </tr>
  </table>
  {% endif %}
  {% buttons submit='OK'%}{% endbuttons %}
</form>
{# Read the documentation for more information #}
{% endblock %}

web/frontend/templates/frontend/add_label_pos_examples.html
{% extends 'frontend/base.html' %}
{% load bootstrap3 %}

{% block title %}Create additional positive matches {% endblock %}
{% block content %}

{# Display a form #}
<form action="{% url 'frontend:add_label_pos_examples' job.id %}" method="post" class="form">
  {% csrf_token %}
  <Table>
  <tr>
  {% for pairA in form.firstPairA %}
  <td>{% bootstrap_field pairA %}</td>
  {% endfor %} 
  </tr>
  <tr>
  {% for pairB in form.firstPairB %}
  <td>{% bootstrap_field pairB show_label=False %}</td>
  {% endfor %} 
  </tr>
  </table>

  {% if form.hasSecondPair %}
  <Table>
  <tr>
  {% for pairA in form.secondPairA %}
  <td>{% bootstrap_field pairA %}</td>
  {% endfor %} 
  </tr>
  <tr>
  {% for pairB in form.secondPairB %}
  <td>{% bootstrap_field pairB show_label=False %}</td>
  {% endfor %} 
  </tr>
  </table>
  {% endif %}
  {% buttons submit='OK'%}{% endbuttons %}
</form>
{# Read the documentation for more information #}
{% endblock %}

web/frontend/templates/frontend/base.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}CloudMatch{% endblock %}</title>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'libs/bootstrap-3.3.5/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'libs/bootstrap-3.3.5/css/bootstrap-theme.css' %}">
    <link rel="stylesheet" href="{% static 'libs/bootstrap-3.3.5/css/bootstrap.css' %}">
    <!--<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
    <!--<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.11.2/css/bootstrap-select.min.css">
    <style>
        body {
            padding-top: 50px;
            padding-bottom: 20px;
        }
    </style>
    <!--<link rel="stylesheet" href="{% static 'libs/font-awesome-4.3.0/css/font-awesome.min.css' %}">-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <!--[if lt IE 9]>
        <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <script>window.html5 || document.write('<script src="{{ STATIC_URL }}libs/html5shiv.js"><\/script>')</script>
    <![endif]-->
    {% block extra-head %}{% endblock %}
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'frontend:index' %}">CloudMatcher</a>
            </div>
            <div class="navbar-collapse collapse" id="navbar-main">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'frontend:index' %}">Home</a>
                    </li>
                    <li>
                        <a href="#">History</a>
                    </li>
                    <li>
                        <a href="#">Progress Monitor</a>
                    </li>
                    <li>
                        <a href="#">Task Monitoring</a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a href="#">Profile</a></li>
                    <li> <a href="#">Logged In ({{ user.username }})</a></li>
                    <li><a href="{% url 'frontend:logout' %}">
                        <span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block content %}(no content){% endblock %}
    </div>
    {% block scripts %}{% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.11.2/js/bootstrap-select.min.js"></script>
    <script src="{% static "libs/bootstrap-checkbox.min.js" %}"></script>
    <script src="{% static "libs/fwidget.js" %}"></script>
    <script src="{% static "libs/fileupload.js" %}"></script>
    <script src="{% static "libs/cmupload.js" %}"></script>
    <script src="https://use.fontawesome.com/3614bc904a.js"></script>
</body>
</html>

web/frontend/templates/frontend/datafile_form.html
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Upload" />
</form>

web/frontend/templates/frontend/detail.html
<h1>Job ID {{ job.id }}</h1>
<ul>
    <li>{{ job.fileA.name }}</li>
    <li>{{ job.fileB.name }}</li>
</ul>
<h2>Job State: {{job.jobstate}}</h2>

<h3>Schema</h3>
{% for j in job.headerA %}
{{ j}} <br />
{% endfor %}

web/frontend/templates/frontend/detail2.html
{% include 'frontend/detail.html' %}
THIS IS THE SECOND

{% for p in top20 %}
<p>{{p}}</p>
{% endfor %}

web/frontend/templates/frontend/index.html
{% extends 'frontend/base.html' %}
{% block content %}
{% load static %}
{% load filters %}
{% static "" as baseUrl %}

<div class="page-header" id="banner">
    <div class="center-align" id="greetings" style="font-size: large; font-family: Roboto; font-size: 25px;">
        <h3>Select what to work on from the below options.</h3>
    </div>
    {% if info_text %}
    <div class="well-small" style="overflow: scroll; max-height: 50px; height: auto; border-bottom: groove">
        <a class="fragment">
            <div>
                <span id="close" onclick='this.parentNode.parentNode.parentNode.removeChild(this.parentNode.parentNode); return false;'><i class="fa fa-window-close" aria-hidden="true"></i></span>
                <p class="text center-align" style="font-size: medium; font-family: Roboto; color: #5cb85c"> {{ info_text }}</p>
            </div>
        </a>
    </div>
    {% endif %}
    <br>
    <div class="col-md-12" style="display: none">
        <p>
            <div id="login_user">{{ username }}</div>
        </p>
    </div>
  <div class="row">
<!--
      <div class="col-md-12">
        <h4 style="font-family: Roboto;"><u>Current running jobs</u></h4>
      </div>
-->
    <div class="col-md-12 center-align">
        <div class="well" style="overflow: scroll; max-height: 250px; height: auto; border-bottom: groove">
            {% if wf_list %}
            <h4 style="font-family: Roboto;"><u>List of running workflows</u></h4>
            <table class="table table-striped table-bordered table-hover">
                <thead class="thead-inverse">
                <tr>
                    <th class="center-align">WF Id</th>
                    <th class="center-align">Workflow name</th>
                    <th class="center-align">Submitted by</th>
                    <th class="center-align">Template</th>
                    <th class="center-align">Current fragment Id</th>
                    <th class="center-align">Status</th>
                    <th class="center-align">Action required from user</th>
                    <th>
                        More info
                        <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span>
                    </th>
                </tr>
                </thead>
                {% for wf in wf_info %}
                <tbody>
                <tr>
                    <td><a href="{% url 'frontend:wf_progress' wf.id %}">{{ wf.id }}</a></td>
                    <td>{{ wf.name }}</td>
                    <td>{{ wf.owner }}</td>
                    <td>{{ wf.template }}</td>
                    <td>{{ wf.curr_frag_id }}</td>
                    <td>{{ state_description|hash:wf.status }}</td>
                    <td>
                        {% if wf.curr_frag_name == "get_table" %}
                        <input type="button" name="theButton" id="started-step" value="Upload dataset" class="btn btn-primary" data-wfid="{{ wf.id }}" data-fragid="{{ wf.curr_frag_id }}">
                        {% else %}
                            {% if wf.curr_frag_name == "get_confirmation" %}
                            <input type="button" name="theButton" id="profile-step" value="View Profile" class="btn btn-success" data-wfid="{{ wf.id }}" data-userid="{{ wf.owner }}">
                            {% endif %}
                        {% endif %}
                    </td>
                    <td><a href="#">View progress</a></td>
                </tr>
                </tbody>
                {% endfor %}
            </table>
            {% else %}
            <p style="font-size: large; color: #5cb85c"><strong>Currently there are no running workflow's. If you are looking for a list of completed jobs, click on the History tab at the top of the page.</strong></p>
            {% endif %}
            </table>
        </div>

        <div class="section-tout">
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-sm-6">
                        <h3><i class="glyphicon glyphicon-cloud-upload"></i> <a href="{% url 'frontend:upload_data' %}">Upload a new dataset</a></h3>
                        <p>Start by uploading a dataset that you would like to browse or use in EM. Upon upload, we will profile your dataset and provide statistics.</p>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <h3><i class="glyphicon glyphicon-circle-arrow-right"></i> <a href="#">Identify matching pairs</a></h3>
                        <p>Select two dataset to be matched and we will perform entity matching for you and return matching pairs as result.</p>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <h3><i class="fa fa-wpexplorer"></i> <a href="#">Browse workspace</a></h3>
                        <p>Getting to know your data is important and so we help you browse all the tables in your workspace be it an uploaded table, matching results, or any intermediate metadata.</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-4 col-sm-6">
                        <h3><i class="glyphicon glyphicon-stats"></i> <a href="#">Current running jobs</a></h3>
                        <p>Find out the status of all the running jobs submitted by you. In addition, the dashboard will also tell you if there is an input required from you to execute the job.</p>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <h3><i class="glyphicon glyphicon-tasks"></i> <a href="#">Current running tasks</a></h3>
                        <p>See and monitor the tasks running behind the job. Some tasks might need an input from you to finish processing. The dashboard will let you know if an input is required for task completion..</p>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <h3><i class="glyphicon glyphicon-wrench"></i> <a href="#">Manage settings</a></h3>
                        <p>Manage your crowdsourcing, account settings in a secured way. CloudMatcher allows you to configure payment settings here.</p>
                    </div>
                </div>
            </div>
            <hr>
            <footer>
                <p>&copy; 2017 CloudMatcher.io, UW-Madison.</p>
            </footer>
        </div>
    </div>
  </div>
</div>
{% endblock %}
{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
  <script language="javascript">

      $("#started-step[type='button']").click(function () {
        var wf_id = $(this).data('wfid');
        var frag_id = $(this).data('fragid');
        window.location = '/upload_data?wf_id=' + wf_id + '&frag_id=' + frag_id;
      });

      $("#profile-step[type='button']").click(function () {
        var wf_id = $(this).data('wfid');
        var user_id = $(this).data('userid');
        window.location = '/view_profile?wf_id=' + wf_id + '&user=' + user_id;
      });

  </script>
{% endblock %}

web/frontend/templates/frontend/jobadd.html
{% extends 'frontend/base.html' %}
{% load bootstrap3 %}

{% block title %}Upload two tables{% endblock %}
{% block content %}
{# Display a form #}
<form action="/frontend/job/add/" method="post" class="form" enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons submit='OK' reset="Cancel" %}{% endbuttons %}
</form>

{# Read the documentation for more information #}

{% endblock %}

web/frontend/templates/frontend/label_neg_examples.html
{% extends 'frontend/base.html' %}
{% load bootstrap3 %}

{% block title %}Select at least two non-matching pairs{% endblock %}

{% block content %}
<form action="{% url 'frontend:label_neg_examples' job.id %}" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons submit='OK'%}{% endbuttons %}
</form>

{# Read the documentation for more information #}
{% endblock %}

web/frontend/templates/frontend/label_pos_examples.html
{% extends 'frontend/base.html' %}
{% load bootstrap3 %}

{% block title %}Select at least two matching pairs (specifically click on Yes to mark a pair as match){% endblock %}

{% block content %}
<form action="{% url 'frontend:label_pos_examples' job.id %}" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons submit='OK'%}{% endbuttons %}
</form>

{# Read the documentation for more information #}
{% endblock %}

web/frontend/templates/frontend/pending.html
{% extends 'frontend/base.html' %}
{% load bootstrap3 %}

{% block title %}Extracting Potential Pairs{% endblock %}
{% block content %}
{% include 'frontend/detail.html' %}

<h2>CloudMatch is still processing your uploaded tables. Please refresh this page in a few minutes</h2>
{% endblock %}

web/frontend/templates/frontend/question_needed.html
{% extends 'frontend/base.html' %}
{% load bootstrap3 %}

{% block title %}Please provide a question for crowdsourcing{% endblock %}
{% block content %}

{# Display a form #}
<form action="{% url 'frontend:question_needed' job.id %}" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons submit='OK'%}{% endbuttons %}
</form>
{# Read the documentation for more information #}
{% endblock %}

web/frontend/templates/frontend/todo.html
{% extends 'frontend/base.html' %}
{% load bootstrap3 %}

{% block title %}TODO page{% endblock %}
{% block content %}
{% include 'frontend/detail.html' %}

<h3>This is a job state we haven't handled yet</h3>
{% endblock %}