web/cloudmatch/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Jul 17 Login Change
from django.views.generic import RedirectView


from wisconsin import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name ='index'),
    url(r'^lake_to_site/(?P<id>.+)/', views.lake_to_site, name ='lake_to_site'),
    url(r'^lake_to_site_download/(?P<id>.+)/', views.lake_to_site_download, name ='lake_to_site_download'),
    url(r'^site_to_lake/', views.site_to_lake, name ='site_to_lake'),
    url(r'^waterbodies/(?P<page>\d+)/', views.waterbodies, name ='waterbodies'),
    url(r'^lake/(?P<id>.+)/', views.lake_detail, name ='lake_detail'),
    url(r'^sites/(?P<page>\d+)/', views.sites, name ='sites'),
    url(r'^site/(?P<id>.+)/', views.site_detail, name ='site_detail'),
    url(r'^bbs/', views.bb, name ='bbs'),
    url(r'^bb/(?P<id>.+)/', views.bb_detail, name ='bb_detail'),
    url(r'^characteristics/', views.characteristics, name ='characteristics'),
    url(r'^characteristics_summary/(?P<char>.+)/', views.characteristics_summary, name ='characteristics_summary'),
    url(r'^characteristics_graph/(?P<charac>.+)/', views.characteristics_graph, name ='characteristics_graph'),
    # July 17 Login Change
    #url(r'^frontend/', include('frontend.urls',namespace='frontend',app_name='frontend')),
    #url(r'^$', RedirectView.as_view(permanent=False, url='/frontend/ulogin/')),
    #url(r'^', include('frontend.urls')),
    # url(r'^frontend/', include('frontend.urls')),
    # July 17 End


    # url(r'^accounts/login/$', login, {'template_name': 'admin/login.html'}, name='login'),
    # url(r'^accounts/logout/$', logout, name='logout'),
    # url(r'^', include('frontend.urls')),
    # url(r'^login/$', login, {'template_name': 'login.html', 'authentication_form': LoginForm}),
    # url(r'^logout/$', logout, {'next_page': '/login'}),
]

urlpatterns += staticfiles_urlpatterns()

web/frontend/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'frontend'
urlpatterns = [
    # ...
    # Login and home page related URLs
    url(r'^homepage/$', homepage, name='homepage'),
    url(r'^main_page/$', main_page, name='main_page'),
    url(r'^$', home, name='home'),
    url(r'^ulogin/$', auth_views.login, {'template_name': 'userreg/home.html'}, name='login'),
    url(r'^ulogout/$', auth_views.logout, {'template_name': 'userreg/logged_out.html'},  name='logout'),
    url(r'^register/$', register, name='register'),
    url(r'^index/$', index, name='index'),

    # Upload dataset URL
    url(r'upload_data/$', upload_data, name='upload_data'),

]

web/frontend/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField, JSONField


# Create your models here.

class DataFile(models.Model):
    file = models.FileField(blank=True, upload_to="data")

    def __str__(self):
        return self.file.name


# YG - creating a model to store dag related information. This model will be used by meta core to store
# DAG related information and to track current DAG status.
class Workflow(models.Model):
    STATES = (
        ('CREATED', 'Workflow created'),
        ('STARTED', 'Workflow started'),
        ('IN_PROGRESS', 'Workflow in progress'),
        ('COMPLETED', 'Workflow completed'),
        ('ERROR', 'Error in workflow'),
        ('CANCELLED', 'Workflow cancelled'),
    )
    name = models.CharField(max_length=50, null=True, blank=True)
    owner = models.ForeignKey("auth.User")
    template_id = models.CharField(max_length=50, null=True, blank=True)
    current_fragment_id = models.CharField(max_length=100, null=True, blank=True)
    status = models.CharField(choices=STATES, max_length=50, blank=True, null=True)
    workflow = models.CharField(max_length=2000, null=True, blank=True)
    info = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return str(self.id)

web/frontend/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django import forms
from django.utils.safestring import mark_safe
from django.contrib.auth.forms import AuthenticationForm
import pandas as pd
from io import BytesIO
from .tasks import *
import re


class PersonalInfoForm(forms.Form):
    job_name = forms.CharField(label='Job Name', max_length=100,
                               widget=forms.TextInput(attrs={'placeholder': 'Enter Job Name'}))
    email = forms.EmailField(label='Email',
                             widget=forms.TextInput(attrs={'placeholder': 'Enter Email address to notify'}))
    email2 = forms.EmailField(label='Confirm Email',
                              widget=forms.TextInput(attrs={'placeholder': 'Confirm you Email address'}))


# YG
class UploadDatasetForm(forms.Form):
    wfid = forms.CharField(label='Workflow ID',
                           max_length=100, required=True,
                           widget=forms.TextInput(attrs={'placeholder': 'Workflow ID'}))
    fragid = forms.CharField(label='Fragment ID', max_length=100, required=True,
                             widget=forms.TextInput(attrs={'placeholder': 'Fragment ID'}))
    name = forms.CharField(label='Name*',
                           help_text='The file uploader will appear once you enter the dataset name',
                           max_length=100, required=True,
                           widget=forms.TextInput(attrs={'placeholder': 'Please enter your dataset name'}))
    description = forms.CharField(label='Description (optional)', max_length=100, required=False,
                                  widget=forms.Textarea(attrs={'placeholder': 'Describe your data here.', 'rows': '2'}))

    docfile = forms.FileField(label='Choose file')


class RegistrationForm(forms.Form):
    username = forms.CharField(label='Username',
                               max_length=100, required=True,
                               widget=forms.TextInput(attrs={'placeholder': 'Please enter a username'}))
    password1 = forms.CharField(label='Password',
                                max_length=100, required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Please enter a password'}))
    password2 = forms.CharField(label='Re-enter password',
                                max_length=100, required=True,
                                widget=forms.PasswordInput(attrs={'placeholder': 'Please reenter your password'}))
    # email = forms.CharField(label='Email*',max_length=100, required=True,
    #                        widget=forms.TextInput(attrs={'placeholder': 'Please enter a username'}))
    email = forms.EmailField(label='Email', required=True)

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2:
                return password2
        raise forms.ValidationError('Passwords do not match.')

    def clean_username(self):
        username = self.cleaned_data['username']
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError('Username can only contain alphanumeric characters and the underscore.')
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError('Username is already taken.')


class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
    password = forms.CharField(label="Password", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'password'}))


class FileUploadForm(forms.Form):
    docfile = forms.FileField(label='Select a file',
                              help_text='max. 42 megabytes')
    days = forms.ChoiceField(widget=forms.Select(), choices=([('1', '1'), ('2', '2'), ('3', '3'), ]), initial=1,
                             required=False)


class FileUploadFormList(forms.Form):
    def __init__(self, *args, **kwargs):
        self.header = kwargs.pop('header')
        options = []
        for head in self.header:
            options.append((head, head))
        super(FileUploadFormList, self).__init__(*args, **kwargs)
        self.fields['list'] = forms.ChoiceField(widget=forms.Select(
            attrs={'class': 'selectpicker show-tick show-menu-arrow', 'data-width': "fit",
                   'data-style': "btn-warning"}), choices=[(o, o) for o in self.header], initial=self.header[0],
            required=False)


def getPairCountDropDownField():
    numbers = range(1, 21)
    return forms.ChoiceField(widget=forms.Select(
        attrs={'class': 'selectpicker show-tick show-menu-arrow', 'data-width': "fit", 'data-style': "btn-warning"}),
        choices=[(i, i) for i in numbers], initial=numbers[4], required=True)


class SelectModeForm(forms.Form):
    pair_count = getPairCountDropDownField()
    docfile = forms.FileField(required=False, label='Select a file', help_text='max. 42 megabytes')


class SelectCrowdModeForm(forms.Form):
    docfile = forms.FileField(required=False, label='Select a file', help_text='max. 42 megabytes')
    pair_count = getPairCountDropDownField()
    reward_amount = forms.FloatField(label='Reward amount for labelling each batch',
                                     help_text='Tooltip description goes here for reward amount',
                                     widget=forms.TextInput(
                                         attrs={'type': 'number', 'step': 0.01, 'class': "form-control", 'min': 0}))
    assignment_duration_hit = forms.IntegerField(label='Assignment duration for this HIT (hours)',
                                                 help_text='Tooltip description goes here for assignment duration',
                                                 widget=forms.TextInput(
                                                     attrs={'type': 'number', 'class': "form-control", 'min': 0}))
    auto_approval_delay = forms.IntegerField(label='Auto Approval Delay (days)',
                                             help_text='Tooltip description goes here for auto approval delay',
                                             widget=forms.TextInput(
                                                 attrs={'type': 'number', 'class': "form-control", 'min': 0}))
    hit_lifetime = forms.IntegerField(label='HIT lifetime (days)',
                                      help_text='Tooltip description goes here for hit lifetime',
                                      widget=forms.TextInput(
                                          attrs={'type': 'number', 'class': "form-control", 'min': 0}))
    initial_assignment = forms.IntegerField(label='Number of Initial Assignment',
                                            help_text='Tooltip description goes here for initial assignment',
                                            widget=forms.TextInput(
                                                attrs={'type': 'number', 'class': "form-control", 'min': 0}))
    mturk_access_key = forms.CharField(label='MTurk Access Key', max_length=300,
                                       help_text='Tooltip description goes here for mturk_access_key',
                                       widget=forms.TextInput(attrs={'type': 'text', 'class': "form-control"}))
    mturk_secret_key = forms.CharField(label='MTurk Secret Key', max_length=300,
                                       help_text='Tooltip description goes here for mturk_secret_key',
                                       widget=forms.TextInput(attrs={'type': 'text', 'class': "form-control"}))


class JobProgressForm(forms.Form):
    job_id = forms.IntegerField(label='Job ID', help_text='Enter Job ID to get the progress',
                                widget=forms.TextInput(attrs={'type': 'number', 'class': "form-control", 'min': 1}))

web/frontend/templates/userreg/home.html
{% extends 'base_home.html' %}
{% block content %}
{% load static %}
<div class="page-header" id="banner">
    <div class="row">
        <div class="col-md-12 center-align">
            <div>
                <h1 style="color: #1e2f45;">CloudMatcher</h1>
                <p class="lead" style="color: #0f0f0f">CloudMatcher lets you upload datasets, browse your data and identify matching records between two uploaded datasets.</p>
            </div>
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
                <!-- Wrapper for slides -->
                <div class="carousel-inner" style="max-height: 250px; margin: 0 auto">
                    <div class="item active" style="max-height: 250px; margin: 0 auto">
                        <img src={% static "images/bg7.jpg" %} alt="" style="width:100%;">
                        <div class="container">
                            <div class="carousel-caption">
                                <h3>CloudMatcher version 0.2.0 to come soon.</h3>
                                <p class="lead">CloudMatcher team is coming up with new changes in 0.2.0 soon. Stay tuned.</p>
                                <a class="btn btn-large btn-primary" href="#">Learn more</a>
                            </div>
                        </div>
                    </div>

                    <div class="item" style="max-height: 250px; margin: 0 auto">
                        <img src={% static "images/bg7.jpg" %} alt="" style="width:100%;">
                        <div class="container">
                            <div class="carousel-caption">
                                <h3>Want to learn about CloudMatcher?</h3>
                                <p class="lead">If you are a first time user, we recommend reading the documentation. Please click here.</p>
                                <a class="btn btn-large btn-primary" href="#">Learn more</a>
                            </div>
                        </div>
                    </div>

                    <div class="item" style="max-height: 250px; margin: 0 auto">
                        <img src={% static "images/bg7.jpg" %} alt="" style="width:100%;">
                        <div class="container">
                            <div class="carousel-caption">
                                <h3>New features !!</h3>
                                <p class="lead">Now, you can upload and browse all your tables online. Please click here to know more.</p>
                                <a class="btn btn-large btn-primary" href="#">New features</a>
                            </div>
                        </div>
                    </div>

                </div>
                <!-- Left and right controls -->
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <div class="form-box">
                    <div class="form-top">
                        <div class="form-top-left">
                            <h3 style="color: #3c3c3c;">Login to CloudMatcher</h3>
                            <p>All fields are required</p>
                        </div>
                        <div class="form-top-right">
                            <i class="fa fa-key"></i>
                        </div>
                    </div>
                    <div class="form-top">
                        <form role="form" method="post" class="login-form" enctype="multipart/form-data" action="{% url 'frontend:login' %}">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="sr-only" for="id_username">Username</label>
                                <input type="text" name="username" placeholder="Enter username ..." class="username form-control" id="id_username" required="required">
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="id_password">Password</label>
                                <input type="password" name="password" placeholder="Enter password ..." class="password form-control" id="id_password" required="required">
                            </div>
                            <button type="submit" class="btn" style="font-size: large">Sign in!</button>
                            <input type="hidden" name="next" value=""/>
                        </form>
                    </div>
                </div>
                <div>
                    {% if form.errors %}
                    <p style="color: red"><strong>Your username and password didn't match. Please try again.</strong></p>
                    {% endif %}
                </div>
            </div>
            <div class="col-md-1 middle-border"></div>
            <div class="col-md-1"></div>
            <br>
            <br>
            <div class="col-md-5">
                <p style="font-family: Roboto; font-size: large; color: #1e2f45"><b>New users - </b> Please create an account to use CloudMatcher services and read the documentation.</p>
                <hr>
                <p><a href="{% url 'frontend:register' %}" class="btn btn-large btn-primary disabled" style="height: 40px; width: 150px; font-size: large">Create Account</a>
                <a class="btn btn-primary btn-large" style="height: 40px; width: 150px; font-size: large">Learn more &raquo;</a>
                </p>
                <br>
                <p class="center-align">Currently, the new registration button is disabled. Please send us an email at uwcloudmatcher@gmail.com for more details.</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}

web/frontend/templates/userreg/logged_out.html
{% extends 'bkupbase.html' %}
{% load i18n %}

{% load bootstrap3 %}

{% block content %}

<p>Thanks for spending some quality time with the Web site today.</p>

<p><a href="{% url 'frontend:login' %}">Log in again</a></p>

{% endblock %}

web/frontend/templates/userreg/login.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block title %}Login{% endblock %}


{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

{% if user.is_authenticated %}
	<p>Welcome, {{ user.username }}</p>

{% else %}
	<form method="post" action="{% url 'frontend:login' %}">
	{% csrf_token %}

	{% bootstrap_form form %}
	{% buttons %}
	<input type="submit" value="Login" />
	<input type="hidden" name="next" value="{{ next }}" />
	{% endbuttons %}

	</form>

	{# Assumes you setup the password_reset view in your URLconf #}
</p>
	{% endif %}

{% endblock %}

web/frontend/templates/userreg/profile.html
{% extends 'base_home.html' %}


{% load bootstrap3 %}

{% block title %}Login{% endblock %}


{% block content %}
{% if user.is_authenticated %}
	<p>Welcome, {{ user.username }}</p>
	<p>This is your profile.</p>
	<p>Also your dashboard.</p>

{% endif %}
{% endblock %}

web/frontend/templates/userreg/register.html
{% extends 'base_home.html' %}
{% block content %}
{% load static %}
<div class="page-header" id="banner">
    <div class="row">
        <h2>CloudMatcher: Account creation step</h2>
    </div>
    <div class="col-md-12 center-align">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <div class="form-box">
                    <div class="form-top">
                        <div class="form-top-left">
                            <h3>Create an account now to use CloudMatcher</h3>
                            <p>All fields are required.</p>
                        </div>
                        <div class="form-top-right">
                            <i class="fa fa-pencil"></i>
                        </div>
                    </div>
                    <div class="form-top">
                        <form role="form" method="post" class="login-form" enctype="multipart/form-data" action="#">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="sr-only" for="id_username">Username</label>
                                <input type="text" name="username" placeholder="Enter username" class="username form-control" id="id_username">
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="id_password1">Password</label>
                                <input type="password" name="password1" placeholder="Enter password" class="password1 form-control" id="id_password1">
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="id_password2">RePassword</label>
                                <input type="password" name="password2" placeholder="Enter password again" class="password2 form-control" id="id_password2">
                            </div>
                            <div class="form-group">
                                <label class="sr-only" for="id_email">Email</label>
                                <input type="text" name="email" placeholder="Enter an email..." class="email form-control" id="id_email">
                            </div>
                            <button type="submit" class="btn">Create Account</button>
                        </form>
                    </div>
                </div>
                <div>
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    {{ field.label }}<strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>
</div>
{% endblock %}

web/frontend/templates/userreg/test.html
{% extends 'frontend/base.html' %}
{% block content %}
{% load static %}
<div class="page-header" id="banner">
  <div class="row">
    <div class="col-md-12 center-align">

        <!--<p class="lead">A powerful tool that finds matches between two datasets. We apply machine learning and crowdsourcing techniques to identify matching records between two datasets and use big data framework to solve problems of scaling. </p>-->
        <div class="well">
            <h1>Welcome to CloudMatcher.io!</h1>
            <p class="lead">CloudMatcher.io lets you upload datasets, explore your data and identify matching records between two uploaded datasets in a scalable way.</p>
            <p><b>First-time users?</b> Please read more to understand CloudMatcher and go through the documentation or tutorials.</p>
            <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
        </div>

        <div class="container">
          <!-- Example row of columns -->
            <div class="row">
                <div class="col-md-4">
                    <img class="marketing-img" width="70px" height="50px" src={% static "images/upload_icon.png" %}/>
                    <br>
                    <br>
                    <h2>Upload a new dataset</h2>
                    <p>Start by uploading a dataset to CloudMatcher that you would like to explore or use in identifying matching pairs. Upon uploading, we will provide you a profile statistics on your uploaded dataset. </p>
                    <p>
                        <a href="{% url 'frontend:upload_data'%}" class="btn btn-success" href="#" role="button">
                            <i class='glyphicon glyphicon-upload'></i>
                            Upload a new dataset
                        </a>
                    </p>
                </div>
                <div class="col-md-4">
                    <img class="marketing-img" width="70px" height="70px" src={% static "images/Data_Analysis.png" %}/>
                    <h2>Explore your data</h2>
                    <p>Getting insights from the data is important and so CloudMatcher helps you explore and understand your data. Our goal is to identify matching definition upon understanding the dataset thoroughly. </p>
                    <p>
                        <a href="{% url 'frontend:create-personal' 0 %}" class="btn btn-success" href="#" role="button">
                            <i class="glyphicon glyphicon-zoom-in"></i>
                            Explore data
                        </a>
                    </p>
                </div>
                <div class="col-md-4">
                    <img class="marketing-img" width="100px" height="50px" src={% static "images/em.png" %}/>
                    <br>
                    <br>
                    <h2>Identify matching pairs</h2>
                    <p>Entity Matching (EM) finds disparate data instances that refer to the same real-world entity. CloudMatcher aims to be a fast, easy-to-use, scalable, and highly available EM service on the Web.</p>
                    <p>
                        <a class="btn btn-success" href="#" role="button">
                            <i class="glyphicon glyphicon-circle-arrow-right"></i>
                            Entity Matching
                        </a>
                    </p>
                </div>
            </div>

            <hr>

            <footer>
                <p>&copy; 2017 CloudMatcher.io, UW-Madison.</p>
            </footer>
        </div> <!-- /container -->

<!--        <a href="{% url 'frontend:create-personal' 0 %}" class="btn btn-primary">Create a new job</a>
        <a href="{% url 'frontend:job_statistics' %}" class="btn btn-success">Jobs submitted</a>-->
    </div>
  </div>
</div>

<!--
<div class="row">
  <div class="col-md-12">
    <div class="col-md-12">
      <img src={% static "images/stage_home.png" %}/>
    </div>
  </div>
</div>
-->

{% endblock %}