web/cloudmatch/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Jul 17 Login Change
from django.views.generic import RedirectView


from wisconsin import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name ='index'),
    url(r'^lake_to_site/(?P<id>.+)/', views.lake_to_site, name ='lake_to_site'),
    url(r'^lake_to_site_download/(?P<id>.+)/', views.lake_to_site_download, name ='lake_to_site_download'),
    url(r'^site_to_lake/', views.site_to_lake, name ='site_to_lake'),
    url(r'^waterbodies/(?P<page>\d+)/', views.waterbodies, name ='waterbodies'),
    url(r'^lake/(?P<id>.+)/', views.lake_detail, name ='lake_detail'),
    url(r'^sites/(?P<page>\d+)/', views.sites, name ='sites'),
    url(r'^site/(?P<id>.+)/', views.site_detail, name ='site_detail'),
    url(r'^bbs/', views.bb, name ='bbs'),
    url(r'^bb/(?P<id>.+)/', views.bb_detail, name ='bb_detail'),
    url(r'^characteristics/', views.characteristics, name ='characteristics'),
    url(r'^characteristics_summary/(?P<char>.+)/', views.characteristics_summary, name ='characteristics_summary'),
    url(r'^characteristics_graph/(?P<charac>.+)/', views.characteristics_graph, name ='characteristics_graph'),
    # July 17 Login Change
    #url(r'^frontend/', include('frontend.urls',namespace='frontend',app_name='frontend')),
    #url(r'^$', RedirectView.as_view(permanent=False, url='/frontend/ulogin/')),
    #url(r'^', include('frontend.urls')),
    # url(r'^frontend/', include('frontend.urls')),
    # July 17 End


    # url(r'^accounts/login/$', login, {'template_name': 'admin/login.html'}, name='login'),
    # url(r'^accounts/logout/$', logout, name='logout'),
    # url(r'^', include('frontend.urls')),
    # url(r'^login/$', login, {'template_name': 'login.html', 'authentication_form': LoginForm}),
    # url(r'^logout/$', logout, {'next_page': '/login'}),
]

urlpatterns += staticfiles_urlpatterns()

web/frontend/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'frontend'
urlpatterns = [
    # ...
    # Login and home page related URLs
    url(r'^homepage/$', homepage, name='homepage'),
    url(r'^main_page/$', main_page, name='main_page'),
    url(r'^$', home, name='home'),
    url(r'^ulogin/$', auth_views.login, {'template_name': 'userreg/home.html'}, name='login'),
    url(r'^ulogout/$', auth_views.logout, {'template_name': 'userreg/logged_out.html'},  name='logout'),
    url(r'^register/$', register, name='register'),
    url(r'^index/$', index, name='index'),

    # Upload dataset URL
    url(r'upload_data/$', upload_data, name='upload_data'),

]

web/wisconsin/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class B2S(models.Model):
    sno = models.IntegerField(blank=True, null=True)
    bb_id = models.TextField(primary_key=True)
    site_id = models.TextField()

    class Meta:
        managed = False
        db_table = 'wisconsin\".\"b2s'
        unique_together = (('bb_id', 'site_id', 'bb_id', 'site_id', 'bb_id', 'site_id', 'bb_id', 'site_id'),)


class Boundingbox(models.Model):
    sno = models.IntegerField(blank=True, null=True)
    bb_id = models.TextField(primary_key=True)
    north = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    south = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    west = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    east = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'wisconsin\".\"boundingbox'
        unique_together = (('bb_id', 'bb_id', 'bb_id', 'bb_id'),)


class Sites(models.Model):
    sno = models.IntegerField(blank=True, null=True)
    site_id = models.TextField(primary_key=True)
    organizationformalname = models.TextField(blank=True, null=True)
    organizationidentifier = models.TextField(blank=True, null=True)
    monitoringlocationname = models.TextField(blank=True, null=True)
    monitoringlocationtypename = models.TextField(blank=True, null=True)
    monitoringlocationdescriptiontext = models.TextField(blank=True, null=True)
    huceightdigitcode = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    drainageareameasure_measurevalue = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    drainageareameasure_measureunitcode = models.TextField(blank=True, null=True)
    contributingdrainageareameasure_measurevalue = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    contributingdrainageareameasure_measureunitcode = models.TextField(blank=True, null=True)
    latitudemeasure = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    longitudemeasure = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    sourcemapscalenumeric = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    horizontalaccuracymeasure_measurevalue = models.TextField(blank=True, null=True)
    horizontalaccuracymeasure_measureunitcode = models.TextField(blank=True, null=True)
    horizontalcollectionmethodname = models.TextField(blank=True, null=True)
    horizontalcoordinatereferencesystemdatumname = models.TextField(blank=True, null=True)
    verticalmeasure_measurevalue = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    verticalmeasure_measureunitcode = models.TextField(blank=True, null=True)
    verticalaccuracymeasure_measurevalue = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    verticalaccuracymeasure_measureunitcode = models.TextField(blank=True, null=True)
    verticalcollectionmethodname = models.TextField(blank=True, null=True)
    verticalcoordinatereferencesystemdatumname = models.TextField(blank=True, null=True)
    countrycode = models.TextField(blank=True, null=True)
    statecode = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    countycode = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    aquifername = models.TextField(blank=True, null=True)
    formationtypetext = models.TextField(blank=True, null=True)
    aquifertypename = models.TextField(blank=True, null=True)
    constructiondatetext = models.TextField(blank=True, null=True)
    welldepthmeasure_measurevalue = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    welldepthmeasure_measureunitcode = models.TextField(blank=True, null=True)
    wellholedepthmeasure_measurevalue = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'wisconsin\".\"sites'
        unique_together = (('site_id', 'site_id', 'site_id', 'site_id'),)


class W2B(models.Model):
    sno = models.IntegerField(blank=True, null=True)
    nhd_lake_id = models.TextField()
    bb_id = models.TextField(primary_key=True)

    class Meta:
        managed = False
        db_table = 'wisconsin\".\"w2b'
        unique_together = (('bb_id', 'nhd_lake_id', 'bb_id', 'nhd_lake_id', 'bb_id', 'nhd_lake_id', 'bb_id', 'nhd_lake_id'),)


class W2S(models.Model):
    sno = models.IntegerField(blank=True, null=True)
    nhd_lake_id = models.TextField()
    gnis_lake_name = models.TextField(blank=True, null=True)
    site_id = models.TextField(primary_key=True)
    monitoringlocationname = models.TextField(blank=True, null=True)
    isinsidelake = models.NullBooleanField()
    disttoshore_m = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'wisconsin\".\"w2s'
        unique_together = (('site_id', 'nhd_lake_id', 'site_id', 'nhd_lake_id', 'site_id', 'nhd_lake_id', 'site_id', 'nhd_lake_id'),)


class Waterbodies(models.Model):
    sno = models.IntegerField(blank=True, null=True)
    nhd_lake_id = models.TextField(primary_key=True)
    gnis_name = models.TextField(blank=True, null=True)
    gnis_id = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    area_sqkm = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    elevation_feet = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    ftype = models.IntegerField(blank=True, null=True)
    fcode = models.IntegerField(blank=True, null=True)
    fdate = models.DateField(blank=True, null=True)
    shape_leng_decimaldegrees = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)
    shape_area_sqdecimaldegrees = models.DecimalField(max_digits=65535, decimal_places=65535, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'wisconsin\".\"waterbodies'
        unique_together = (('nhd_lake_id', 'nhd_lake_id', 'nhd_lake_id', 'nhd_lake_id'),)

web/wisconsin/forms.py
from django import forms

class LakeToSiteForm(forms.Form):
	lake_id = forms.CharField(widget=forms.TextInput(
			attrs={
				'id' : 'l2s_lake_id',
				'class' : 'form-control',
				'placeholder' : 'Enter Lake ID (e.g. 37649095)...',
				'required' : 'true',
			}
		), label='')


class SiteToLakeForm(forms.Form):
	site_id = forms.CharField(widget=forms.TextInput(
			attrs={
				'class' : 'form-control',
				'placeholder' : 'Enter Site ID (e.g. USGS-443840092400301)...',
				'required' : 'true',
			}
		), label='')

WATER_QUERY_OPTIONS = (  
    ('lake_id', 'Lake ID'),
    ('lake_name', 'Lake Name'),
    ('area', 'Area'),
)

AREA_COMPARATORS = (
		('gt', '>'),
    	('lt', '<'),
    	('exact', '='),
    	('gte', '>='),
    	('lte', '<='),
	)

class WaterbodiesForm(forms.Form):
	 
	  lake_id = forms.CharField(widget=forms.TextInput(
			attrs={
				'class' : 'form-control',
				'placeholder' : 'Enter ID (e.g. 120017988)...',
			}
		), label='', required=False,)
	  lake_name = forms.CharField(widget=forms.TextInput(
			attrs={
				'class' : 'form-control',
				'placeholder' : 'Enter Name (e.g. Coon Lake)...',
			}
		), label='', required=False,)
	  area_cmp = forms.ChoiceField(choices=AREA_COMPARATORS, widget=forms.Select(
	  				attrs={'class':'form-control',
	  						'id' : 'waterbodies-area-cmp',
	  						'style' : 'border:none; background-color:#e9ecef;'
	  				}))
	  area = forms.DecimalField(widget=forms.TextInput(
			attrs={
				'class' : 'form-control',
				'placeholder' : 'Enter Area (e.g. 50)...',
			}
		), label='', required=False,)
	  fcode = forms.IntegerField(widget=forms.TextInput(
			attrs={
				'class' : 'form-control',
				'placeholder' : 'Enter Feature Code (e.g. 39004)...',
			}
		), label='', required=False,)


class SitesForm(forms.Form):
	 # query_options = forms.ChoiceField(choices=WATER_QUERY_OPTIONS, widget=forms.Select(
	  #				attrs={'class':'form-control',
	  #						'id' : 'waterbodies-dropdown',
	  #				}))
	  site_id = forms.CharField(widget=forms.TextInput(
			attrs={
				'class' : 'form-control',
				'placeholder' : 'Enter Site ID (e.g. USGS-444522093102600)...',
			}
		), required=False,)
	  org_name = forms.CharField(widget=forms.TextInput(
			attrs={
				'class' : 'form-control',
				'placeholder' : 'Enter Organization name...',
			}
		), label='', required=False,)
	  org_id = forms.CharField(widget=forms.TextInput(
			attrs={
				'class' : 'form-control',
				'placeholder' : 'Enter Organization ID (e.g. USGS-MN)...',
			}
		), label='', required=False,)
	  huc = forms.DecimalField(widget=forms.TextInput(
			attrs={
				'class' : 'form-control',
				'placeholder' : 'Enter 8-digit HUC (e.g. 7040001)...',
			}
		), label='', required=False,)


class BoundingBoxForm(forms.Form):
	  east = forms.DecimalField(widget=forms.TextInput(
			attrs={
				'class' : 'form-control',
				'placeholder' : 'Enter East Longitude (e.g. -91.2427227688)...',
				'required' : 'true',
			}
		), label='', )
	  west = forms.DecimalField(widget=forms.TextInput(
			attrs={
				'class' : 'form-control',
				'placeholder' : 'Enter West Longitude (e.g. -91.2545777688)...',
				'required' : 'true',
			}
		), label='', )
	  north = forms.DecimalField(widget=forms.TextInput(
			attrs={
				'class' : 'form-control',
				'placeholder' : 'Enter North Latitude (e.g. 43.4081387326)...',
				'required' : 'true',
			}
		), label='',)
	  south = forms.DecimalField(widget=forms.TextInput(
			attrs={
				'class' : 'form-control',
				'placeholder' : 'Enter South Latitude (e.g. 43.3915035993)...',
				'required' : 'true',
			}
		), label='', )

web/templates/wisconsin/bb.html
{% extends "base.html" %}

{% block content %}
	<!--a href="{% url 'index' %}">
		Back to Home
	</a-->
	<div class="grey-wrapper">
		{% if bbs %}
			<div class="row">
				<div class="col-md-12">
					<h3 id="heading">Bounding Boxes
					</h3>
				</div>
			</div>
			<div class="row top-buffer">
			
				<div class="col-md-12">
					<table class="table table-hover table-bordered table-responsive" style="background: #ffffff;">
						<thead>
							<tr class="bootstrap-blue-bg">
								<th>Bounding Box ID</th>
								<th>North</th>
								<th>South</th>
								<th>East</th>
								<th>West</th>
							</tr>
						</thead>
						
						<tbody>
							{% for b in bbs %}
								<tr>
									<td><a href="{% url 'bb_detail' b.bb_id %}">{{ b.bb_id }}</a></td>
									<td>{{ b.south | floatformat:5 }}</td>
									<td>{{ b.north | floatformat:5 }}</td>
									<td>{{ b.east | floatformat:5 }}</td>
									<td>{{ b.west | floatformat:5 }}</td>
								</tr>
							{% endfor %}
						</tbody>
						
					</table>
				</div>
			</div>
		{% else %}
			<div class="row">

				<div class="col-md-12">
					<h4>No data found</h4>
				</div>
			</div>
			
		{% endif %}
	</div>
	
	

{% endblock content %} 

web/templates/wisconsin/bb_detail.html
{% extends "base.html" %}

{% block content %}

	<div class="grey-wrapper">
		
			<div class="row">
				<div class="col-md-12">
					<h3 id="heading">Bounding box Details for {{ bb_id }}
					</h3>
				</div>
			</div>
			{% if lake %}
				<div class="row top-buffer">
					<div class="col-md-12 top-buffer">
						{% for l in lake %}
							<h6>Water body ID : <a href="{% url 'lake_detail' l.nhd_lake_id %}">{{ l.nhd_lake_id }}</a>
							</h6>
						
							<h6>Water body Name : {{ l.gnis_name }}
							</h6>

							
						{% endfor %}
					</div>
				</div>
			{% else %}
				<div class="row">

					<div class="col-md-12">
						<h4>No lake data found</h4>
					</div>
				</div>
				
			{% endif %}

			{% if sites %}
				
				<div class="row top-buffer">
					<div class="col-md-12 top-buffer">
					
					<h6>Sites (<a href ="{% url 'lake_to_site' lake_id %}"> View Sites on Map </a>) :  
					</h6>
						
						
					</div>
				</div>
				<div class="row top-buffer">
			
					<div class="col-md-12">
						<table class="table table-hover table-bordered table-responsive" style="background: #ffffff;">
							<thead>
								<tr class="bootstrap-blue-bg">
									<th>Site ID</th>
									<th>Org Name</th>
									<th>Org Id</th>
									<th>HUC</th>
									<th>Monitoring Location</th>
									<th>Location Type</th>
									<th>Location Description</th>
								</tr>
							</thead>
							
							<tbody>
								{% for s in sites %}
									<tr>
										<td><a href="{% url 'site_detail' s.site_id %}">{{ s.site_id }}</a></td>
										<td>{{ s.organizationformalname }}</td>
										<td>{{ s.organizationidentifier }}</td>
										<td>{{ s.huceightdigitcode | floatformat:0 }}</td>
										<td>{{ s.monitoringlocationname }}</td>
										<td>{{ s.monitoringlocationtypename }}</td>
										<td>{{ s.monitoringlocationdescriptiontext }}</td>
									</tr>
								{% endfor %}
							</tbody>
							
						</table>
					</div>
				</div>
			{% else %}
				<div class="row">

					<div class="col-md-12">
						<h4>No site data found</h4>
					</div>
				</div>
				
			{% endif %}
			
		
	</div>

{% endblock content %} 

web/templates/wisconsin/index.html
{% extends "base.html" %}

{% block content %}
	<div class="row">
		<div class="col-md-5">
			<div class="form-box" style="padding-bottom: 30px;">
                <div class="form-top">
                    <div class="form-top-left">
                    	<h3>Query Waterbodies 
                    		<!--i class="fa fa-info-circle" aria-hidden="true" style="font-size: 12px; vertical-align: middle;" data-toggle="tooltip" data-placement="top" title="Retrieves details about specific waterbodies based on the query parameter passed."></i-->
                    	</h3>
                    	
                    </div>
                </div>
                <div class="form-top">
	                    	<i>Retrieves details about specific waterbodies based on the parameter(s) passed.</i>
	                    
                </div>
                <div class="form-top">
                	<form action="/waterbodies/1/" method="GET">	
                		{{ form_waterbodies.non_field_errors }}
                		<!--div class="form-group">
					        {{ form_waterbodies.query_options.errors }}
					        <label for="id_query_options">Query using:</label>
					        {{ form_waterbodies.query_options }}
						    
				    	</div-->
				    	<div class="form-group"  id="lake_name_tb">
					        {{ form_waterbodies.lake_name.errors }}
					        <label class="sr-only" for="id_lake_name">Lake Name:</label>
					        {{ form_waterbodies.lake_name }}
						    
				    	</div>
				    	<div class="form-group" id="lake_id_tb">
					        {{ form_waterbodies.lake_id.errors }}
					        <label class="sr-only" for="id_lake_id">Lake ID:</label>
					        {{ form_waterbodies.lake_id }}
						    
				    	</div>
				    	<div class="form-group"  id="area_tb">
					        {{ form_waterbodies.area_cmp.errors }}
					        {{ form_waterbodies.area.errors }}
					        <div class="input-group">
					        	<span class="input-group-addon" style="padding: 0px;">
						        <label class="sr-only" for="id_area_cmp">Query using:</label>
						        {{ form_waterbodies.area_cmp }}
						        </span>
						        <label class="sr-only" for="id_area">Area:</label>
						        {{ form_waterbodies.area }}
						        <span class="input-group-addon" style="padding: 0px;">sq. km.</span>
					        </div>
						    
				    	</div>
				    	<div class="form-group"  id="fcode_tb">
					        {{ form_waterbodies.fcode.errors }}
					        <label class="sr-only" for="id_fcode">Fcode:</label>
					        {{ form_waterbodies.fcode }}
						    
				    	</div>
				    	{% csrf_token %}
			  			<button type="submit" class="btn" style="font-size: large">Submit</button>
				    </form> 
                </div>
            </div>
		</div>
		<div class="col-md-1 middle-border"></div>
        <div class="col-md-1"></div>
	    <br>
	    <br>
	    <div class="col-md-5">
	    	<div class="form-box" style="padding-bottom: 30px;">
                <div class="form-top">
                    <div class="form-top-left">
                    	<h3>Query Sites 
                    		<!--i class="fa fa-info-circle" aria-hidden="true" style="font-size: 12px; vertical-align: middle;" data-toggle="tooltip" data-placement="top" title="Retrieves details about specific sites based on the query parameter passed."></i-->
                    	</h3>
                    </div>
                </div>
                <div class="form-top">
	                    	<i>Retrieves details about specific sites based on the parameter(s) passed.</i>
	                    
                </div>
                <div class="form-top">
                	<form action="/sites/1/" method="GET">	
                		{{ form_sites.non_field_errors }}
                		<!--div class="row form-group">
                			
                				{{ form_sites.site_id.errors }}
                				<div class="col-md-3" style="margin-top:12px;">
                					<label for="id_query_options">Site ID:</label>
                				</div>
						        
						        <div class="col-md-9">
						        	{{ form_sites.site_id }}
						        </div>
						        
							    
                			
				    	</div-->
				    	<div class="form-group" id="org_name_tb">
					        {{ form_sites.site_id.errors }}
					        <label class="sr-only" for="id_lake_id">Site ID:</label>
					        {{ form_sites.site_id }}
						    
				    	</div>
				    	<div class="form-group" id="org_name_tb">
					        {{ form_sites.org_name.errors }}
					        <label class="sr-only" for="id_lake_id">:</label>
					        {{ form_sites.org_name }}
						    
				    	</div>
				    	<div class="form-group"  id="lake_name_tb">
					        {{ form_sites.org_id.errors }}
					        <label class="sr-only" for="id_lake_name">:</label>
					        {{ form_sites.org_id }}
						    
				    	</div>
				    	<!--div class="form-group"  id="area_tb">
					    
					        {{ form_sites.monitoring_location.errors }}
					       
					        	
						        <label class="sr-only" for="id_area">:</label>
						        {{ form_sites.monitoring_location }}
					       
						    
				    	</div-->
				    	<div class="form-group"  id="area_tb">
					    
					        {{ form_sites.huc.errors }}
					       
					        	
						        <label class="sr-only" for="id_huc">HUC:</label>
						        {{ form_sites.huc }}
					       
						    
				    	</div>
				    	{% csrf_token %}
			  			<button type="submit" class="btn" style="font-size: large">Submit</button>
				    </form> 
                </div>
            </div>
	    </div>	
	</div>
	<hr>
	<div class="row">
		<div class="col-md-12">
		    <div class="form-box" style="padding-bottom: 30px;">
		    	<div class="row form-top">
			    	<div class="col-md-5">
		                <div class="form-top">
		                    <div class="form-top-left" style="width: 90%;">
		                    	<h3>Query Bounding Boxes
		                    	</h3>
		                    </div>
		                </div>
		                <div class="form-top">
			                    	<i>Obtains bounding box coordinates for waterbodies that lie within the specified latitudes and longitudes and subsequently, retrieves the sites associated with each of them. Each bounding box is associated with a water body.</i>
			                    
		                </div>
		            </div>
		           

			        <div class="col-md-2"></div>
				    <br>
				    <br>
				    <div class="col-md-5" style="margin-top:30px;">
				    	<div class="form-top">
		                	<form action="/bbs/" method="POST">	
		                		{{ form_bb.non_field_errors }}
						    	<div class="form-group" id="org_name_tb">
							        {{ form_bb.north.errors }}
							        <label class="sr-only" for="id_lake_id">Site ID:</label>
							        {{ form_bb.north }}
								    
						    	</div>
						    	<div class="form-group" id="org_name_tb">
							        {{ form_bb.south.errors }}
							        <label class="sr-only" for="id_lake_id">:</label>
							        {{ form_bb.south }}
								    
						    	</div>
						    	<div class="form-group"  id="lake_name_tb">
							        {{ form_bb.east.errors }}
							        <label class="sr-only" for="id_lake_name">:</label>
							        {{ form_bb.east }}
								    
						    	</div>
						    	<div class="form-group"  id="lake_name_tb">
							        {{ form_bb.west.errors }}
							        <label class="sr-only" for="id_lake_name">:</label>
							        {{ form_bb.west }}
								    
						    	</div>
						    	
						    	{% csrf_token %}
					  			<button type="submit" class="btn" style="font-size: large">Submit</button>
						    </form> 
		                </div>
				    </div>
	            </div>    
	        	
		    </div>
		</div>
		<!--div class="col-md-1 middle-border"></div>
        <div class="col-md-1"></div>
	    <br>
	    <br>
	    <div class="col-md-5"></div-->
	</div>
	<hr>
	<div class="row">
		<div class="col-md-5">
			<div class="form-box">
                <div class="form-top">
                    <div class="form-top-left">
                    	<h3>Lake to Site 
                    		<!--i class="fa fa-info-circle" aria-hidden="true" style="font-size: 12px; vertical-align: middle;" data-toggle="tooltip" data-placement="top" title="Retrieves site details related to a lake."></i-->
                    	</h3>
                    	
                    </div>
                    
                    
                </div>
                <div class="form-top">
	                    	<i>Obtains sites associated with a lake by providing the Lake ID</i>
	                    
                </div>
                <div class="form-top">
                	<form id="forml2s" method="POST" >	
                		<div class="form-group">
				    		{{ form.as_p }}
				    	</div>
				    	{% csrf_token %}
			  			<button type="submit" onclick="onL2SSubmit();" class="btn" style="font-size: large">Submit</button>
				    </form> 
                </div>
            </div>
		</div>
		<div class="col-md-1 middle-border"></div>
        <div class="col-md-1"></div>
	    <br>
	    <br>
	    <div class="col-md-5">
			<div class="form-box">
                <div class="form-top">
                    <div class="form-top-left">
                    	<h3>Site to Lake 
                    		<!--i class="fa fa-info-circle" aria-hidden="true" style="font-size: 12px; vertical-align: middle;" data-toggle="tooltip" data-placement="top" title="Retrieves the lake details related to a site."></i-->
                    	</h3>
                    </div>
                </div>
                <div class="form-top">
	                    	<i>Obtains the lake associated with a site by providing the Site ID</i>
	                    
                </div>
                <div class="form-top">
                	<form action="/site_to_lake/" method="POST">	
				    	{{ forms2l.as_p }}
				    	{% csrf_token %}
			  			<button type="submit" class="btn" style="font-size: large">Submit</button>
				    </form> 
                </div>
            </div>
		</div>
	</div>
	<hr>
	



{% endblock content %} 